# Generated by Django 5.2.5 on 2025-09-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Menu item title', max_length=255)),
                ('link_url', models.URLField(blank=True, help_text='External URL (leave blank for page link)')),
                ('menu_type', models.CharField(choices=[('main', 'Main Navigation'), ('footer', 'Footer Links')], default='main', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in menu (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this item in the menu')),
                ('link_page', models.ForeignKey(blank=True, help_text='Page to link to (overrides external URL)', null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Main Menu', max_length=255)),
                ('items', models.ManyToManyField(blank=True, related_name='main_menus', to='core.menuitem')),
            ],
            options={
                'verbose_name': 'Main Menu',
                'verbose_name_plural': 'Main Menus',
            },
        ),
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Footer Links', max_length=255)),
                ('items', models.ManyToManyField(blank=True, related_name='footer_menus', to='core.menuitem')),
            ],
            options={
                'verbose_name': 'Footer Menu',
                'verbose_name_plural': 'Footer Menus',
            },
        ),
    ]
