# Generated by Django 5.2.5 on 2025-09-27 20:36

import datetime
import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "send_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to send immediately.",
                        null=True,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "send_timezone",
                    models.CharField(
                        blank=True,
                        help_text="Optional override for scheduling timezone.",
                        max_length=64,
                    ),
                ),
                ("scheduled_task_id", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DripCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "start_strategy",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediately after confirmation"),
                            ("delayed", "Start after a delay"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("start_delay_days", models.PositiveIntegerField(default=0)),
                ("send_time", models.TimeField(default=datetime.time(9, 0))),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Drip campaign",
                "verbose_name_plural": "Drip campaigns",
                "ordering": ["subscription_list__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Supports Django template syntax.", max_length=255
                    ),
                ),
                (
                    "preview_text",
                    models.CharField(
                        blank=True,
                        help_text="Shown in some email clients under the subject.",
                        max_length=150,
                    ),
                ),
                (
                    "html_body",
                    wagtail.fields.RichTextField(
                        help_text="Supports Django template syntax."
                    ),
                ),
                (
                    "text_body",
                    models.TextField(
                        blank=True,
                        help_text="Optional plain text version. Leave blank to auto-generate.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email template",
                "verbose_name_plural": "Email templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text="Used to personalize send times for drip sequences.",
                        max_length=64,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Subscriber",
                "verbose_name_plural": "Subscribers",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="DripStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                (
                    "offset_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Days after start to send this step."
                    ),
                ),
                (
                    "offset_weeks",
                    models.PositiveIntegerField(
                        default=0, help_text="Additional weeks after start."
                    ),
                ),
                (
                    "send_weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Align send to this weekday after offsets.",
                        null=True,
                    ),
                ),
                (
                    "drip_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="newsletter.dripcampaign",
                    ),
                ),
                (
                    "email_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drip_steps",
                        to="newsletter.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drip step",
                "verbose_name_plural": "Drip steps",
                "ordering": ["drip_campaign", "order"],
                "unique_together": {("drip_campaign", "order")},
            },
        ),
        migrations.CreateModel(
            name="EmailMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("bounced_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="newsletter.campaign",
                    ),
                ),
                (
                    "drip_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="newsletter.dripstep",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="newsletter.subscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email log",
                "verbose_name_plural": "Email logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=50)),
                ("recipient", models.EmailField(max_length=254)),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="newsletter.emailmessagelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email event",
                "verbose_name_plural": "Email events",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="email_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="newsletter.emailtemplate",
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending confirmation"),
                            ("active", "Active"),
                            ("unsubscribed", "Unsubscribed"),
                            ("bounced", "Bounced"),
                            ("complained", "Complaint"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "confirmation_token",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "unsubscribe_token",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("confirmation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("opt_in_source", models.CharField(blank=True, max_length=150)),
                ("referrer", models.URLField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="newsletter.subscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.AddField(
            model_name="emailmessagelog",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_logs",
                to="newsletter.subscription",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Display in public subscription forms."
                    ),
                ),
                (
                    "double_opt_in",
                    models.BooleanField(
                        default=True,
                        help_text="Require confirmation before sending newsletters.",
                    ),
                ),
                ("default_from_name", models.CharField(blank=True, max_length=150)),
                ("default_from_email", models.EmailField(blank=True, max_length=254)),
                (
                    "welcome_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional template sent immediately after confirmation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welcome_lists",
                        to="newsletter.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription list",
                "verbose_name_plural": "Subscription lists",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="newsletter.subscriptionlist",
            ),
        ),
        migrations.AddField(
            model_name="dripcampaign",
            name="subscription_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drip_campaigns",
                to="newsletter.subscriptionlist",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="lists",
            field=models.ManyToManyField(
                related_name="campaigns", to="newsletter.subscriptionlist"
            ),
        ),
        migrations.CreateModel(
            name="DripSequenceProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("next_send_at", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drip_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="newsletter.dripcampaign",
                    ),
                ),
                (
                    "last_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_for",
                        to="newsletter.dripstep",
                    ),
                ),
                (
                    "next_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_for",
                        to="newsletter.dripstep",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drip_progress",
                        to="newsletter.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drip progress",
                "verbose_name_plural": "Drip progress records",
                "unique_together": {("drip_campaign", "subscription")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("subscriber", "subscription_list")},
        ),
    ]
