# Generated by Django 5.2.5 on 2025-09-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dripcampaign",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
