# Generated by Django 5.2.5 on 2025-09-13 16:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('lead', 0), ('paragraph', 1), ('heading', 5), ('image', 10), ('pullquote', 13)], block_lookup={0: ('blog.blocks.LeadBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'code', 'h2', 'h3', 'h4']}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3')]}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional custom id', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 2), ('level', 3), ('anchor', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text override', 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full'), ('wide', 'Wide'), ('left', 'Left'), ('right', 'Right')]}), 10: ('wagtail.blocks.StructBlock', [[('image', 6), ('alt', 7), ('caption', 8), ('align', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {}), 12: ('wagtail.blocks.CharBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('quote', 11), ('attribution', 12)]], {})}),
        ),
    ]
