# Generated by Django 5.2.5 on 2025-09-13 16:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('lead', 0), ('paragraph', 1), ('heading', 5), ('image', 10), ('pullquote', 13), ('callout', 15), ('code', 17), ('embed', 18), ('table', 19), ('divider', 20)], block_lookup={0: ('blog.blocks.LeadBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'code', 'h2', 'h3', 'h4']}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3')]}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional custom id', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 2), ('level', 3), ('anchor', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text override', 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full'), ('wide', 'Wide'), ('left', 'Left'), ('right', 'Right')]}), 10: ('wagtail.blocks.StructBlock', [[('image', 6), ('alt', 7), ('caption', 8), ('align', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {}), 12: ('wagtail.blocks.CharBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('quote', 11), ('attribution', 12)]], {}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Tip'), ('warning', 'Warning')]}), 15: ('wagtail.blocks.StructBlock', [[('variant', 14), ('body', 1)]], {}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Plain text'), ('python', 'Python'), ('bash', 'Bash'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('json', 'JSON'), ('sql', 'SQL')]}), 17: ('wagtail.blocks.StructBlock', [[('language', 16), ('code', 11), ('caption', 12)]], {}), 18: ('blog.blocks.EmbedBlock', (), {}), 19: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 20: ('blog.blocks.Divider', (), {})}),
        ),
    ]
